apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpd
    app.kubernetes.io/component: httpd
    app.kubernetes.io/instance: httpd
  name: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: httpd
  template:
    metadata:
      labels:
        deployment: httpd
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/openshift/httpd@sha256:531133cb05887a64f6c5ba8e0f6a7c34f9b39c223ae065e7772d2c3a65dbf65e
        imagePullPolicy: IfNotPresent
        name: httpd
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
